---
# This is a test container and is not intended for production use.
# The passwords are public here to make the setup transparent.
user_setup_password_vagrant: "vagrant"
user_setup_password_salt_vagrant: "qy7skOTCaaiKEMV0"
user_setup_password_ansible: "ansible"
user_setup_password_salt_ansible: "pUxp88aAfO1U7G7q"
user_setup_users:
  - name: "vagrant"
    state: present
    uid: 1000
    shell: "/bin/sh"
    create_home: true
    groups: []
    groups_append: true
    password: "{{ user_setup_password_vagrant | password_hash('sha512', user_setup_password_salt_vagrant) }}"
    sudo_access: true
    sudo_nopasswd: true
    env_var_setup: false
    env_var_file: ".env_vars"
    user_directories: []
    ssh_directory: ".ssh"
    ssh_authorized_keys_exclusive: true
    ssh_authorized_keys:
      # Vagrant insecure public keys
      # https://github.com/hashicorp/vagrant/blob/main/keys/vagrant.pub
      - key: "ssh-rsa AAAAB3NzaC1yc2EAAAABIwAAAQEA6NF8iallvQVp22WDkTkyrtvp9eWW6A8YVr+kz4TjGYe7gHzIw+niNltGEFHzD8+v1I2YJ6oXevct1YeS0o9HZyN1Q9qgCgzUFtdOKLv6IedplqoPkcmF0aYet2PkEDo3MlTBckFXPITAMzF8dJSIFo9D8HfdOV0IAdx4O7PtixWKn5y2hMNG0zQPyUecp4pzC6kivAIhyfHilFR61RGL+GPXQ2MWZWFYbAGjyiYJnAmCP3NOTd0jMZEnDkbUvxhMmBYSdETk1rRgm+R4LOzFUGaHqHDLKLX+FIPKcF96hrucXzcWyLbIbEgE98OHlnVYCzRdK8jlqm8tehUc9c9WhQ== vagrant insecure public key"
      - key: "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIN1YdxBpNlzxDqfJyw/QKow1F+wvG9hXGoqiysfJOn5Y vagrant insecure public key"
  - name: "ansible"
    state: present
    uid: 1001
    shell: "/bin/sh"
    create_home: true
    groups: []
    groups_append: true
    password: "{{ user_setup_password_ansible | password_hash('sha512', user_setup_password_salt_ansible) }}"
    sudo_access: true
    sudo_nopasswd: false
    env_var_setup: false
    env_var_file: ".env_vars"
    user_directories: []
    ssh_directory: ".ssh"
    ssh_authorized_keys_exclusive: true
    ssh_authorized_keys:
      # Vagrant insecure public keys
      # https://github.com/hashicorp/vagrant/blob/main/keys/vagrant.pub
      - key: "ssh-rsa AAAAB3NzaC1yc2EAAAABIwAAAQEA6NF8iallvQVp22WDkTkyrtvp9eWW6A8YVr+kz4TjGYe7gHzIw+niNltGEFHzD8+v1I2YJ6oXevct1YeS0o9HZyN1Q9qgCgzUFtdOKLv6IedplqoPkcmF0aYet2PkEDo3MlTBckFXPITAMzF8dJSIFo9D8HfdOV0IAdx4O7PtixWKn5y2hMNG0zQPyUecp4pzC6kivAIhyfHilFR61RGL+GPXQ2MWZWFYbAGjyiYJnAmCP3NOTd0jMZEnDkbUvxhMmBYSdETk1rRgm+R4LOzFUGaHqHDLKLX+FIPKcF96hrucXzcWyLbIbEgE98OHlnVYCzRdK8jlqm8tehUc9c9WhQ== vagrant insecure public key"
      - key: "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIN1YdxBpNlzxDqfJyw/QKow1F+wvG9hXGoqiysfJOn5Y vagrant insecure public key"
